# Railway nixpacks configuration for Python FastAPI app
[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.virtualenv"]

[phases.install]
cmds = [
  "python --version",
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python FastAPI app build complete'"]

[start]
cmd = "source /opt/venv/bin/activate && uvicorn server:app --host 0.0.0.0 --port $PORT"
