[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
# Add environment variables for better data handling
DATA_PERSISTENCE = "true"
BACKUP_DATA_ON_STARTUP = "true"
# CORS configuration for frontend access
CORS_ORIGINS = "https://web.phoenixtrailers.ca,https://phoenixtrailers.ca,http://localhost:3000"

# Specify the source directory for Railway
[source]
directory = "backend"
